---
# tasks file for role_configure_blender

- name: Create installation directory
  file:
    path: "{{ blender_benchmark_cli_dest }}"
    state: directory
  become: true

- name: Download Blender Benchmark CLI
  get_url:
    url: "{{ blender_benchmark_cli_url }}"
    dest: "/tmp/blender_benchmark_cli.tar.gz"
  become: true

- name: Extract Blender Benchmark CLI
  unarchive:
    src: "/tmp/blender_benchmark_cli.tar.gz"
    dest: "{{ blender_benchmark_cli_dest }}"
    remote_src: yes
  become: true

- name: Set executable permissions for all files in the directory
  file:
    path: "{{ item.path }}"
    mode: '0755'
  with_fileglob:
    - "{{ blender_benchmark_cli_dest }}/**"
  become: true

- name: Set permissions for the directory itself
  file:
    path: "{{ blender_benchmark_cli_dest }}"
    mode: '0775'
  become: true