apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-launcher-
spec:
  entrypoint: launch
  templates:
  - name: launch
    steps:
    - - name: fetch-and-execute
        template: fetch-execute

  - name: fetch-execute
    script:
      image: bitnami/kubectl:latest
      command: [sh, -c]
      source: |
        # Clone the repo containing the main workflow
        git clone https://github.com/helloskyy-io/FluxEdge-AI-Toolbox.git /workspace
        # Navigate to the directory containing the workflow_main.yml
        cd /workspace/deployments/ubuntu_22.04/argo_cd
        # Submit the main workflow stored in Git
        kubectl apply -f workflow_main.yml




