apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      deploymentInformation: ubuntu-deployment
  template:
    metadata:
      labels:
        app: ubuntu
        deploymentInformation: ubuntu-deployment
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
      - name: ubuntu-container
        image: ubuntu:22.04
        resources:
          limits:
            nvidia.com/gpu: 1
        hostNetwork: true
        command: ["/bin/bash"]
        args: ["-c", "apt-get -y update && apt-get -y upgrade && apt-get -y install vim && sleep infinity"]
        ports:
        - containerPort: 80
        - containerPort: 22
        - containerPort: 8888
        - containerPort: 7860
        - containerPort: 3000