apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
    deploymentInformation: ubuntu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deploymentInformation: ubuntu-deployment
  template:
    metadata:
      labels:
        app: ubuntu
        deploymentInformation: ubuntu-deployment
    spec:
      # affinity will be set accordingly by the server
      hostNetwork: true
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
      - name: ubuntu-container
        image: ubuntu:22.04
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["/bin/bash"]
        args:
          - "-c"
          - "apt-get -y update && apt-get -y upgrade && apt-get -y install vim && sleep infinity"
        ports:
        - containerPort: 80
        - containerPort: 22
