apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
  labels:
    app: ubuntu
spec:
  selector:
    deploymentInformation: ubuntu-deployment
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  type: NodePort
