apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
  labels:
    app: ubuntu
spec:
  selector:
    deploymentInformation: ubuntu-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 38888
    - protocol: TCP
      port: 7860
      targetPort: 7860
      nodePort: 37860
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 33000
  type: NodePort
