# AI_Toolbox.yml Playbook
# This playbook allows users to select options for configuring the container environment.

- name: AI Toolbox Playbook
  hosts: localhost
  gather_facts: yes
  
  # Prompt the user to select an option
  vars_prompt:
  - name: "option"
    prompt: |
      " ░▒▓██████▓▒░░▒▓█▓▒░      ░▒▓████████▓▒░▒▓██████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░      
       ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      
       ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      
       ░▒▓████████▓▒░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░░▒▓██████▓▒░       
       ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      
       ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      
       ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░         ░▒▓█▓▒░   ░▒▓██████▓▒░ ░▒▓██████▓▒░░▒▓████████▓▒░▒▓███████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░      
 
       built by pumapumapumas @ Hello Skyy
 
       
       Choose an environment deployment option: (this will configure the container environment)

       1. Configure FluxEdge container for Detectron2 Computer Vision Framework
       2. Future (placeholder)
       3. Throw Bricks at Jefke

       
       Or Choose a project deployment option: (requires above environments)
       
       4. Import Skyy-Net AI framework (uses FluxEdge default ollama environment)
       5. Import Skyy-Med AI for SkyyMed medical imaging applicaiton (uses Detectron2 environment)
       6. Import Open WebUI 

       
       Exit AI Toolbox:
       
       7. Exit AI Toolbox"

    private: no
      
  tasks:
    # Validate the selected option
    - name: Validate the selected option
      block:
        - assert:
            that:
              - option | int in [1, 2, 3, 4, 5, 6, 7]
            msg: "Invalid option. Please choose a valid option (1, 2, 3, 4, 5, 6, or 7)."
      
    # Process selected option
    - name: Process selected option
      block:
        - name: Display selected option
          debug:
            msg: "You selected option {{ option }}"
            
        # Add tasks or roles based on the selected option
        - include_tasks: environment_detectron2.yml
          when: option | int == 1
        
        - debug:
            msg: "Placeholder for future features."
          when: option | int == [2]  

        - include_tasks: bricks.yml
          when: option | int == 3

        - include_tasks: setup_skyynet_ai.yml
          when: option | int == 4

        - include_tasks: setup_detectron2.yml
          when: option | int == 5  

        - debug:
            msg: "Placeholder for future features."
          when: option | int == [6]  
          
      when: option | int in [1, 2, 3, 4, 5, 6]

    # Exit AI Toolbox
    - name: Exit AI Toolbox
      block:
        - debug:
            msg: "Exiting AI Toolbox."
      when: option | int == 7