---
- name: AI Toolbox Playbook
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: "option"
      prompt: |
        "Choose an option:
        1. Configure container for Detectron2 Computer Vision Framework
        2. Import "sample" Jupyter Notebooks for Detectron2 
        3. Throw Bricks at Jefke
        4. Exit AI Toolbox"
      private: no
  tasks:
    - name: Validate the selected option
      block:
        - assert:
            that:
              - option | int in [1, 2, 3, 4]
            msg: "Invalid option. Please choose a valid option (1, 2, 3, or 4)."
      # rescue:
      #   - debug:
      #       msg: "Invalid option. Please choose a valid option (1, 2, 3, or 4)."
      #   - set_fact:
      #       option: null
      #   - continue

    - name: Process selected option
      block:
        - name: Display selected option
          debug:
            msg: "You selected option {{ option }}"

        # Add tasks or roles based on the selected option
        # Task examples:
        # - include_tasks: detectron2_setup.yml
        #   when: option == 1
        # - include_tasks: detectron2_notebooks.yml
        #   when: option == 2
        # - include_tasks: throw_bricks_at_jefke.yml
        #   when: option == 3

      when: option | int in [1, 2, 3]

    - name: Exit AI Toolbox
      block:
        - debug:
            msg: "Exiting AI Toolbox."
      when: option | int == 4
