# AI_Toolbox.yml Playbook
# This playbook allows users to select options for configuring the container environment.

- name: AI Toolbox Playbook
  hosts: localhost
  gather_facts: no
  
  # Prompt the user to select an option
  vars_prompt:
  - name: "option"
    prompt: |
      " ░▒▓██████▓▒░░▒▓█▓▒░      ░▒▓████████▓▒░▒▓██████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░      
       ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      
       ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      
       ░▒▓████████▓▒░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░░▒▓██████▓▒░       
       ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      
       ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░         ░▒▓█▓▒░  ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      
       ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░         ░▒▓█▓▒░   ░▒▓██████▓▒░ ░▒▓██████▓▒░░▒▓████████▓▒░▒▓███████▓▒░ ░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░      
 
       built by pumapumapumas @ Hello Skyy
 
       Choose an environment deployment option:
       1. Configure FluxEdge container for Detectron2 Computer Vision Framework
       2. Future (Placeholder)
       3. Throw Bricks at Jefke

       Or Choose a project deployment option:
       4. Import SkyyNet AI for SkyyMed medical imaging applicaiton (uses Detectron2 environment)
       5. Import SkyyMed medical imaging conputer vision project (for Detectron2 environment)
       6. Future (placeholder) 

       Exit AI Toolbox:
       7. Exit AI Toolbox"

    private: no
      
  tasks:
    # Validate the selected option
    - name: Validate the selected option
      block:
        - assert:
            that:
              - option | int in [1, 3, 7]
            msg: "Invalid option. Please choose a valid option (1, 3, or 7)."
      
    # Process selected option
    - name: Process selected option
      block:
        - name: Display selected option
          debug:
            msg: "You selected option {{ option }}"
            
        # Add tasks or roles based on the selected option
        - include_tasks: detectron2_setup.yml
          when: option | int == 1
        - include_tasks: bricks.yml
          when: option | int == 3
        - include_tasks: detectron2_notebooks.yml
          when: option | int == 4
      when: option | int in [1, 3, 4]

    # Exit AI Toolbox
    - name: Exit AI Toolbox
      block:
        - debug:
            msg: "Exiting AI Toolbox."
      when: option | int == 7