# /AI-Toolbox/ansible/playbooks/environment_stable_diffusion.yml

# This playbook calls roles as necessary to configure the packages and dependencies
# necessary to create a base container environment for the Stable Diffusion model and UI.


#### this section of code only installs general packages at their "latest" version ####

# Task to update the apt cache
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes
  changed_when: false

# Task to install python3-pip and other utilities
- name: Install pip and other basic utilities
  apt:
    name:
      - python3      # Install Python 3
      - python3-pip  # Install pip for Python 3
      - nano         # Install nano 
      - wget         # Install wget to pull datasets
      - iputils-ping # Install basic networking tools
    state: latest  # Ensures the latest version is installed
  become: yes


#### from this point down, specific dependancies or versions of packages required by Detectron2 are installed as roles


- name: Configure New User
  include_role:
    name: role_configure_new_user
  vars:
    user_to_add: "{{ sd_user }}"
    user_password: "{{ sd_password }}"
    add_to_sudoers: "{{ sd_sudoers }}"

- name: Configure pyenv
  include_role:
    name: role_configure_pyenv
  vars:
    user: "{{ sd_user }}"
    configure_python: true
    python_version: "{{ 3.10.0 }}"  
    activate_env: true

- name: Install Stable Diffusion and 1111 UI
  include_role:
    name: role_configure_stable_diffusion



# - name: Configure Docker
#   include_role:
#     name: role_configure_docker
  
# - name: Configure Open Web UI
#   include_role:
#     name: role_configure_open_ui

# - name: Configure opencv for Detectron2
#   include_role:
#     name: role_configure_opencv    

# - name: Configure cython for Detectron2
#   include_role:
#     name: role_configure_cython        

# - name: Configure pycoco tools for Detectron2
#   include_role:
#     name: role_configure_pycoco    

# - name: Configure Detectron2
#   include_role:
#     name: role_configure_detectron2            