# /AI-Toolbox/ansible/playbooks/skyynet_setup.yml

- name: Clone SkyyNet Repository
  include role:
    name: clone_repository
  vars:
    repository_url: "{{ skyy_net_url }}"
    destination_path: "{{ skyy_net_destination_path }}"
