- name: restart jupyter notebook
  block:
    - name: Check if Jupyter is running
      shell: pgrep -f "jupyter-notebook"
      register: jupyter_running
      ignore_errors: true

    - name: Kill running Jupyter Notebook if exists
      shell: pkill -f "jupyter-notebook"
      when: jupyter_running.rc == 0

    - name: Start Jupyter Notebook
      shell: |
        nohup jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser > /var/log/jupyter.log 2>&1 &
  become: true
  async: 10
  poll: 0