---
# tasks file for import_skyy_net

# roles/import_skyy_net/tasks/main.yml
- name: Ensure Git is installed
  apt:
    name: git
    state: present
  become: true

- name: Check if Skyy-Net directory exists
  ansible.builtin.stat:
    path: /Skyy-Net
  register: skyy_net_dir

- name: Clone Skyy-Net repository using Bash script
  ansible.builtin.shell: |
    git clone {{ repository_url }} {{ destination_path }}
  args:
    executable: /bin/bash
  vars:
    repo: "{{ repository_url }}"
    dest: "{{ destination_path }}"
  become: true

