# main.yml for role_configure_pytorch
# This role installs latest pytorch (currently works with Detectron2 but may need to version lock in the future)

- name: Install PyTorch, torchvision, and torchaudio with pip
  pip:
    name:
      - torch
      - torchvision
      - torchaudio
    state: latest
