# this role installs Detectron2
# this is a pip install from a github source, so in order to make the instlalation process idempotant
# it first clones it locally to "opt" then it installs only if there is a change to the download. 

- name: Ensure the /opt/github_packages directory exists
  file:
    path: /opt/github_packages
    state: directory
    mode: '0755'
  become: yes

- name: Clone Detectron2 repository into /opt/github_packages
  git:
    repo: 'https://github.com/facebookresearch/detectron2.git'
    dest: '/opt/github_packages/detectron2'
    clone: yes
    update: yes
  register: git_clone_detectron2
  become: yes

- name: Install Detectron2 from the local clone if updated
  pip:
    name: '/opt/github_packages/detectron2'
    state: latest
  when: git_clone_detectron2.changed
  become: yes