# main.yml for role_configure_jupyter
# This role installs Jupyter Notebooks web server 
# the handler restarts the webserver only if the install occurs (making it idempotant)

- name: Install Jupyter Notebook
  pip:
    name: notebook
    state: latest
  notify: restart jupyter notebook
