# main.yml for role_configure_jupyter
# This role installs Jupyter Notebooks web server and starts it

- name: Install Jupyter Notebook
  pip:
    name: notebook
    state: latest

- name: Kill any existing Jupyter Notebook processes
  ansible.builtin.shell: pkill -f "jupyter-notebook"
  ignore_errors: true

- name: Start Jupyter Notebook
  ansible.builtin.shell: |
    nohup jupyter notebook --ip=0.0.0.0 --allow-root --no-browser > /var/log/jupyter.log 2>&1 &
  become: yes