# main.yml for role_configure_jupyter
# This role installs Jupyter Notebooks web server 
# the handler restarts the webserver only if the install occurs (making it idempotant)

- name: Install Jupyter Notebook
  pip:
    name: notebook
    state: latest
  # notify: restart jupyter notebook

- name: Start jupyter notebook
  block:
    - name: Check if Jupyter Notebook is running
      shell: pgrep -f "jupyter-notebook"
      register: jupyter_process
      ignore_errors: true
      failed_when: false  # This prevents the task from failing and suppresses the red error message

    - name: Start Jupyter Notebook
      shell: |
        nohup jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser &> /var/log/jupyter.log &
      async: 10
      poll: 0
      when: jupyter_process.rc != 0
