---
# tasks file for role_configure_stable_diffusion

- name: Ensure installation directory exists
  file:
    path: "{{ sd_install_path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
  become: true
  become_user: "{{ user }}"

- name: Install python3.10-venv
  apt:
    name:
      - python3.10-venv
    state: latest
  become: true

- name: Clone Stable Diffusion web UI repository
  git:
    repo: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui.git'
    dest: "{{ sd_install_path }}/stable-diffusion-webui"
    version: "main"
  become: true
  become_user: "{{ user }}"

- name: Set up Python virtual environment
  command:
    cmd: "python3.10 -m venv venv"
    chdir: "{{ sd_install_path }}/stable-diffusion-webui"
  become: true
  become_user: "{{ user }}"

- name: Run webui.sh within a virtual environment
  command:
    cmd: "./venv/bin/python webui.sh --listen --api"
    chdir: "{{ sd_install_path }}/stable-diffusion-webui"
  async: 0
  poll: 0
  register: webui_process
  become: true
  become_user: "{{ user }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
