apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ubuntu-deployment-
spec:
  entrypoint: deploy
  templates:
  - name: deploy
    container:
      image: bitnami/kubectl:latest
      command: [sh, -c]
      args: |
        # Apply the base folder using Kustomize
        kubectl apply -k /workspace/deployment_configs/base

