apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ubuntu-deployment-
spec:
  serviceAccountName: batch-job-sa
  nodeSelector:
    kubernetes.io/hostname: "" # This is the node the workflow will run on. This will be provided by FluxEdge dynamically
  entrypoint: main
  arguments:
    parameters:
      - name: repoUrl
        value: "https://github.com/helloskyy-io/FluxEdge-AI-Toolbox.git"  # Public repository URL
      - name: repoBranch
        value: "main"  # Branch to clone
      # Node Selector will be dynamically added by FluxEdge
      # Deployment Information will be dynmically added by FluxEdge
  templates:
  - name: main
    steps:
      - - name: clone-repo
          template: clone-repo
          arguments:
            parameters:
              - name: repoUrl
                value: "{{workflow.parameters.repoUrl}}"
              - name: repoBranch
                value: "{{workflow.parameters.repoBranch}}"

      - - name: kustomize-build
          template: kustomize-build
          arguments:
            parameters:
              - name: nodeSelector
                value: "{{workflow.parameters.nodeSelector}}"
              - name: deploymentInformation
                value: "{{workflow.parameters.deploymentInformation}}"
            artifacts:
              - name: repo
                from: "{{steps.clone-repo.outputs.artifacts.repo}}"

      - - name: apply-kubectl
          template: apply-kubectl
          arguments:
            artifacts:
              - name: manifests
                from: "{{steps.kustomize-build.outputs.artifacts.manifests}}"

  - name: clone-repo
    inputs:
      parameters:
        - name: repoUrl
        - name: repoBranch
    container:
      image: alpine/git
      command: [sh, -c]
      args: [
        "git clone --branch {{inputs.parameters.repoBranch}} {{inputs.parameters.repoUrl}} /workspace && ls /workspace"
      ]
    outputs:
      artifacts:
        - name: repo
          path: /workspace

  - name: kustomize-build
    inputs:
      artifacts:
        - name: repo
          path: /workspace
    script:
      image: line/kubectl-kustomize
      command: [sh]
      source: |
        #!/bin/sh
        cd /workspace/deployments/ubuntu_22.04/deployment_configs/overlays/primary
        # Replace placeholders in kustomization.yaml with actual values
        sed -i "s/\NODE_SELECTOR/{{inputs.parameters.nodeSelector}}/g" deployment-patch.yaml
        sed -i "s/\DEPLOYMENT_INFORMATION/{{inputs.parameters.deploymentInformation}}/g" deployment-patch.yaml
        sed -i "s/\DEPLOYMENT_INFORMATION/{{inputs.parameters.deploymentInformation}}/g" service-patch.yaml 
        sed -i "s/\DEPLOYMENT_INFORMATION/{{inputs.parameters.deploymentInformation}}/g" kustomization.yaml 
        # Debug replacements
        # echo "Modified deployment-patch.yaml:"
        # cat deployment-patch.yaml
        # echo "Modified service-patch.yaml:"
        # cat service-patch.yaml# Generate the manifests using kustomize
        kustomize build . -o /workspace/modified
        ls /workspace/modified
    outputs:
      artifacts:
        - name: manifests
          path: /workspace/modified

  - name: apply-kubectl
    inputs:
      artifacts:
        - name: manifests
          path: /workspace/modified
    container:
      image: bitnami/kubectl:1.21
      command: [sh, -c]
      args: |
        echo "Applying manifests..."
        kubectl apply -f /workspace/modified --dry-run=client
        kubectl apply -f /workspace/modified
