
# tasks file for role_configure_docker

# tasks file for role_configure_docker

- name: Update the apt cache
  ansible.builtin.apt:
    update_cache: yes
  ignore_errors: true

- name: Install required packages
  ansible.builtin.apt:
    name: 
      - ca-certificates
      - curl
      - gnupg
    state: present
  ignore_errors: true

- block:
    - name: Ensure the APT keyring directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    
    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.gpg
        mode: '0644'
    
    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        filename: 'docker'
    
    - name: Update apt cache after adding Docker repository
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker and its components
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

  rescue:
    - name: Error Handling Block
      debug:
        msg: "An error occurred, but we are skipping it and continuing with the next tasks."
      ignore_errors: true

- name: Ensure Docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add root to the docker group
  ansible.builtin.user:
    name: "root"
    groups: docker
    append: yes
