
# role_configure_docker.yml
# tasks file for role_configure_docker

- name: Update the apt cache
  ansible.builtin.apt:
    update_cache: yes
  ignore_errors: true

- name: Install required packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
  ignore_errors: true

- block:
    - name: Download and add Docker GPG key
      ansible.builtin.shell:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        executable: /bin/bash

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        filename: 'docker'
        update_cache: yes

    - name: Install Docker and its components
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

  rescue:
    - name: Error Handling Block
      debug:
        msg: "An error occurred, but we are skipping it and continuing with the next tasks."
      ignore_errors: true

- name: Ensure Docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add root to the docker group
  ansible.builtin.user:
    name: "root"
    groups: docker
    append: yes
